# -*- coding: utf-8 -*-
"""Assignemnt5_Cognitive.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/152BGsOWYCQP7t5uzjDx-YyyTLkJn9UkI

***Q1***
"""

import numpy as np
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
total_sum = np.sum(gfg)
total_sum

row_sums = np.sum(gfg, axis=1)
row_sums

col_sums = np.sum(gfg, axis=0)
col_sums

"""***Q2***"""

array = np.array([10, 52, 62, 16, 16, 54, 453])
sorted_array = np.sort(array)
sorted_array

sorted_indices = np.argsort(array)
sorted_indices

smallest_4 = np.sort(array)[:4]
smallest_4

largest_5 = np.sort(array)[-5:]
largest_5

array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

integer_mask == array.astype(int)
integer_elements = array[integer_mask]
integer_elements

float_mask = array != array.astype(int)
float_elements = array[float_mask]
float_elements

"""***Q3***"""

X = 78 + 66
sales = np.array([X, X+50, X+100, X+150, X+200])
sales

tax_rate = ((X % 5) + 5) / 100
tax_rate

sales_af_tax=sales * (1 - tax_rate)
sales_af_tax

discount=sales < X+100

sales_based_on_discount=np.where(discount, sales*0.95, sales*0.90)
sales_based_on_discount

sales_matrix = np.tile(sales, (3, 1))
sales_matrix

increase_weak=np.array([1,1.02,1.04]).reshape(-1,1)
increase_weak

final=sales_matrix*increase_weak
final

"""***Q4***"""

import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(-10, 10, 100)
y1 = x**2
y2 = np.sin(x)
y3 = np.exp(x)
y4 = np.log(np.abs(x) + 1)
plt.figure(figsize=(12, 8))
plt.subplot(2, 2, 1)
plt.plot(x, y1)
plt.title('Y = x²')
plt.grid(True)

plt.subplot(2, 2, 2)
plt.plot(x, y2)
plt.title('Y = sin(x)')
plt.grid(True)

plt.subplot(2, 2, 3)
plt.plot(x, y3)
plt.title('Y = eˣ')
plt.grid(True)

plt.subplot(2, 2, 4)
plt.plot(x, y4)
plt.title('Y = log(|x| + 1)')
plt.grid(True)