# -*- coding: utf-8 -*-
"""Assignment7_Cognitive.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E1kSRlE9VpDdRvTj9_sM30AYpoWaVlp-

***Q1***

***PART 1***

***1***
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
roll_no =  102317162
np.random.seed(roll_no)

"""***2***"""

sales_data = np.random.randint(1000, 5000, size=(12, 4))

"""***3***"""

months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
categories = ['Electronics', 'Clothing', 'Home & Kitchen', 'Sports']
df = pd.DataFrame(sales_data, columns=categories, index=months)
df

"""***PART 2***"""

print("First 5 rows of DataFrame:\n", df.head())
print("\nSummary Statistics:\n", df.describe())

total_sales_category = df.sum()
print("\nTotal Sales per Category:\n", total_sales_category)

df['Total Sales'] = df.sum(axis=1)
df

df['Growth Rate'] = df['Total Sales'].pct_change() * 100
df

df['Electronics'] = df['Electronics'] * 0.9
df

"""***PART 3***"""

plt.figure(figsize=(10, 6))
for category in categories:
    plt.plot(df.index, df[category], label=category)
plt.xlabel('Months')
plt.ylabel('Sales')
plt.title('Monthly Sales Trends')
plt.legend()
plt.show()

plt.figure(figsize=(8, 6))
sns.boxplot(data=df[categories])
plt.title('Sales Distribution by Category')
plt.show()

"""***Q2***"""

array = np.array([[1, -2, 3],[-4, 5, -6]])

np.abs(array)

flat = array.flatten()
flat

np.percentile(flat,[25,50,75])

np.percentile(array,[25,50,75],axis=0)

np.percentile(array,[25,50,75],axis=1)

print(np.mean(flat))
print(np.median(flat))
print(np.std(flat))

print(np.mean(array,axis=0))
print(np.median(array,axis=0))
print(np.std(array,axis=0))

print(np.mean(array,axis=1))
print(np.median(array,axis=1))
print(np.std(array,axis=1))

"""***Q3***"""

a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0])

print("Floor:", np.floor(a))
print("Ceiling:", np.ceil(a))
print("Truncated:", np.trunc(a))
print("Rounded:", np.round(a))

"""***Q4***"""

def swap_list_elements(lst, pos1, pos2):
    temp = lst[pos1]
    lst[pos1] = lst[pos2]
    lst[pos2] = temp
    return lst

lst = [1, 2, 3, 4, 5]
print("Swapped List:", swap_list_elements(lst, 1, 3))

"""***Q5***"""

def swap_set_elements(s, pos1, pos2):
    s_list = list(s)
    s_list[pos1], s_list[pos2] = s_list[pos2], s_list[pos1]
    return set(s_list)

s = {10, 20, 30, 40, 50}
print("Swapped Set:", swap_set_elements(s, 0, 3))

