# -*- coding: utf-8 -*-
"""Assignment4_Cognitive.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YTiBdNEK4mQvQYbZmSyNT60Q6IzIrkmI
"""

#Q1
import numpy as np

arr=np.array([1,2,3,4,5])
print(arr+2)
print(arr*3)
print(arr/2)

#Q2
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])
print(arr[::-1])

def most_frequent(arr):
    values, counts = np.unique(arr, return_counts=True)
    max_count = np.max(counts)
    most_frequent_value = values[np.argmax(counts)]
    indices = np.where(arr == most_frequent_value)[0]
    return most_frequent_value, indices

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

x_value, x_indices = most_frequent(x)
y_value, y_indices = most_frequent(y)

print(f"Most frequent value in x: {x_value}, Indices: {x_indices}")
print(f"Most frequent value in y: {y_value}, Indices: {y_indices}")

#Q3
import numpy as np

arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr)
print(arr[0][1])
print(arr[2][0])

#Q4
import numpy as np

arnav=np.linspace(10,100,25)
print(arnav)
print(arnav.shape)
print(arnav.size)
print(arnav.dtype)
print(arnav.nbytes)
# print(arnav.T)
print(arnav.reshape(25,1))

#Q5
import numpy as np

ucs420_Arnav=np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
print(ucs420_Arnav)

print("Mean: ",np.mean(ucs420_Arnav))
print("Median: ",np.median(ucs420_Arnav))
print("Max: ",np.max(ucs420_Arnav))
print("Min: ",np.min(ucs420_Arnav))
print("Unique elements: ",np.unique(ucs420_Arnav))
print("")
print("Reshaped: ",ucs420_Arnav.reshape(4,3))
print(" ")
print("Resized: ",np.resize(ucs420_Arnav, (2, 3)))

